from __future__ import annotations

from paper_plot_style import FIG_DIR, ROOT


FIGURES = [
    (
        "fig2_architecture",
        "architecture",
        "C1--C5 architecture for residual-driven atlas repair. The differentiable PBR baker attributes held-out relighting residuals, C2 edits only local charts, C3 reallocates a fixed texel budget, C4 checks cross-channel seam behavior, and C5 deploys either the accepted atlas or the rolled-back baseline.",
    ),
    (
        "fig3_comparison",
        "main_comparison",
        "Main B3 comparison on spot and bunny. Positive bars indicate deployed PSNR gain over the initial atlas; labels show whether the C5 gate accepted the repair or rolled back to the baseline.",
    ),
    (
        "fig4_ablation",
        "ablation",
        "B4 ablation effects measured as PSNR change relative to the full method. Hatching marks expected-direction mismatches or missing completed metric rows, exposing the strong PBR-channel signal and weak or zero-signal components.",
    ),
    (
        "fig5_matched",
        "matched_control",
        "Strict matched controls for the accepted PartUV cases. Gains persist when atlas size, padding, or chart count are locked, but vanish under distortion, utilization, or all strict matched controls, indicating a principled downstream-fidelity trade-off.",
    ),
    (
        "fig6_robustness",
        "robustness",
        "Robustness sweeps for the spot/PartUV accepted case. Light and view sweeps remain stable, while the noise sweep keeps the non-monotonic sigma=0.01 rollback anomaly rather than smoothing it away.",
    ),
]


def main() -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    chunks = ["% Auto-generated by figures/scripts/gen_latex_includes.py", ""]
    for name, label, caption in FIGURES:
        chunks.extend(
            [
                rf"% === {name} ===",
                r"\begin{figure}[t]",
                r"  \centering",
                rf"  \includegraphics[width=0.95\linewidth]{{figures/main/{name}.pdf}}",
                rf"  \caption{{{caption}}}",
                rf"  \label{{fig:{label}}}",
                r"\end{figure}",
                "",
            ]
        )
    out = FIG_DIR / "latex_includes.tex"
    out.write_text("\n".join(chunks), encoding="utf-8")
    print(f"Saved: {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
